version: '3.8'

services:

  authservice:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    container_name: authservice
    ports:
      - "5123:5123"
    environment:
      - ASPNETCORE_URLS=http://+:5123

  vehicleservice:
    build:
      context: ./VehicleService
      dockerfile: Dockerfile
    container_name: vehicleservice
    ports:
      - "5183:5183"
    environment:
      - ASPNETCORE_URLS=http://+:5183

  routeservice:
    build:
      context: ./RouteService
      dockerfile: Dockerfile
    container_name: routeservice
    ports:
      - "5184:5184"
    environment:
      - ASPNETCORE_URLS=http://+:5184

  fuelservice:
    build:
      context: ./FuelConsumption
      dockerfile: Dockerfile
    container_name: fuelservice
    ports:
      - "5185:5185"
    environment:
      - ASPNETCORE_URLS=http://+:5185

  driverservice:
    build:
      context: ./DriverService
      dockerfile: Dockerfile
    container_name: driverservice
    ports:
